site_name: Pisound Docs
theme_dir: theme
site_url: https://blokas.io
site_favicon: favicon.ico
extra:
  logo: 'images/logo.svg'
  social:
    - type: 'github'
      link: 'https://github.com/BlokasLabs'
    - type: 'twitter'
      link: 'https://twitter.com/blokaslabs'
    - type: 'facebook'
      link: 'https://www.facebook.com/blokaslabs/'
extra_css:
  - 'css/style.css'
repo_name: 'pisound-docs-wiki'
repo_url: 'https://github.com/BlokasLabs/pisound-docs/wiki'

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde

copyright: 'Copyright &copy; 2017 VILNIAUS BLOKAS UAB'

pages:
- Getting Started: index.md
- Audio: audio.md
- MIDI: midi.md
- Software: software.md
- The Button: the-button.md
- Pisound Mobile App: pisound-app.md
- Pisound & Pure Data: pisound-&-Pure-Data.md
- Pisound App: Pisound-App.md
- MOD Emulator for Pisound: MODEP.md
- Detailed Specs: specs.md
- Example Projects: Example-projects.md
- FAQs: faqs.md
